### ISSUE TITLE
Scanner Error parsing example hosted on YAML website

### ISSUE THREAD

**Issue by kjowens** [dcjones/YAML.jl#20]
I mean the YAML document found here: http://yaml.org/start.html

Copy it into a text document, start julia, import the YAML module, then try to load the file: 

```julia
julia> YAML.load(open("ex1.yaml"))
ERROR: ScannerError("while scanning a tag",line 1, column 4,"expected ' ', but found ^",line 1, column 20)
 in scan_tag at ~/.julia/YAML/src/scanner.jl:981
 in fetch_more_tokens at ~/.julia/YAML/src/scanner.jl:217
 in peek at ~/.julia/YAML/src/scanner.jl:149
 in parse_document_content at ~/.julia/YAML/src/parser.jl:199
 in peek at ~/.julia/YAML/src/parser.jl:47
 in compose_node at ~/.julia/YAML/src/composer.jl:52
 in compose_document at ~/.julia/YAML/src/composer.jl:43
 in compose at ~/.julia/YAML/src/composer.jl:31
 in load at ~/.julia/YAML/src/YAML.jl:26
```
I replaced my actual path with "~" in that code.
here's my version info:

```julia
julia> versioninfo()
Julia Version 0.3.9
Commit 31efe69 (2015-05-30 11:24 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     T8300  @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by dcjones** [comment]
Curiously enough, PyYAML, on which this implementation is based, also doesn't parse this file. It's not obvious to me that the file is correct, because the `^` is unescaped, `clarkevans.com/^invoice` is not a valid URI. I will see what other implementations do, though.

**Comment by dcjones** [comment]
This example is also not parseable by [JS-YAML](http://nodeca.github.io/js-yaml/), nor yaml-cpp.

I don't know what the deal is with this being hosted on yaml.org, but I think YAML.jl is correct in not parsing it.
