### ISSUE TITLE
scan_flow_scalar_breaks

### ISSUE THREAD

**Issue by nico202** [dcjones/YAML.jl#39]
When parsing a valid yaml, i get:
ERROR: MethodError: no method matching scan_flow_scalar_breaks(::Bool, ::YAML.Mark)

**Comment by nico202** [comment]
Here
https://github.com/dcjones/YAML.jl/blob/b469dad382d7be00bd41f75e85bb08029fcfcbac/src/scanner.jl#L1260
the function is called without the required parameter, just adding "stream" as first parameter seems to work

**Comment by sglyon** [comment]
Could you please post a minimal working example so we can make sure to get this resolved and add it to our tests?

Thanks!
