### ISSUE TITLE
Fix deprecation warning and wrong import in julia nightly

### ISSUE THREAD

**Issue by nico202** [dcjones/YAML.jl#44]
Issue created in order to track the state on julia nighly:

1. All usages of immutable -> struct
WARNING: deprecated syntax "immutable" at
Use "struct" instead.

2. All usages of type -> mutable struct
WARNING: deprecated syntax "type" at 
Use "mutable struct" instead.

3. The use of Date
WARNING: importing deprecated binding Base.DateTime into YAML.
ERROR: LoadError: UndefVarErroAll usages of immutable -> structr: Date not defined

4. New sintax 
parametric method syntax decode{T <: Codec}(codec::Type{T}, s::AbstractString)
Use "decode(codec::Type{T}, s::AbstractString) where T <: Codec" instead.

**Comment by mabynke** [comment]
On Julia 0.7.0-beta.275 I am getting a large amount of deprecation warnings by simply loading an empty file using `load()`.
I get _a lot_ of these:
```
WARNING: Base.Void is deprecated, use Nothing instead.
 in module YAML
```
I also get these:
```
┌ Warning: `Array{T, 1}(m::Int) where T` is deprecated, use `Array{T, 1}(undef, m)` instead.
│   caller = Type at buffered_input.jl:14 [inlined]
└ @ Core ~/.julia/packages/YAML/CRQQ/src/buffered_input.jl:14
┌ Warning: `Array{T, 1}(m::Int) where T` is deprecated, use `Array{T, 1}(undef, m)` instead.
│   caller = YAML.TokenStream(::Base.GenericIOBuffer{Array{UInt8,1}}) at scanner.jl:102
└ @ YAML ~/.julia/packages/YAML/CRQQ/src/scanner.jl:102
┌ Warning: `shift!` is deprecated, use `popfirst!` instead.
│   caller = dequeue! at queue.jl:14 [inlined]
└ @ Core ~/.julia/packages/YAML/CRQQ/src/queue.jl:14
┌ Warning: `ismatch(r::Regex, s::AbstractString)` is deprecated, use `occursin(r, s)` instead.
│   caller = resolve(::YAML.Resolver, ::Type{YAML.ScalarNode}, ::String, ::Tuple{Bool,Bool}) at resolver.jl:73
└ @ YAML ~/.julia/packages/YAML/CRQQ/src/resolver.jl:73
```
